- Assets/HealthReplenish.cs
- Assets/Prefabs/Cube.prefab
- Assets/Prefabs/Cube.prefab.meta
- Assets/Scenes/Technical Prototype/CharlesVehicle.unity
- Assets/Scenes/Technical Prototype/Gabby-Driving.unity
- Assets/Scripts/Player.cs
- Added suggestions from previous pull request comments
- Added item to replenish oil
- Player script can be used for player controller
- HealthReplenish can be used for oil replenishment items
> Charles vehicle2

- Assets/Scenes/Technical Prototype/CharlesVehicle.unity
- Charles Scene now has camera movement
> Changed Charles scene to have camera

- Assets/Prefabs/UI_Prefabs/Slot.prefab
- Assets/Scripts/UI/HotbarManager.cs
- Assets/Scripts/UI/HotbarSlot.cs
Separated the cook timer and the patience timer for the hotbar - both update simultaneously.
> Updated Hotbar Functionality

- Assets/LevelSelectManager.cs
- Assets/LevelSelectManager.cs.meta
- Assets/Prefabs/LevelSelector.prefab
- Assets/Prefabs/LevelSelector.prefab.meta
- Assets/Scenes/Technical Prototype/Liam-Menu.unity
- Assets/Scenes/Technical Prototype/Liam-Menu.unity.meta
This is just a scene that contains a main menu, options menu, and level select menu. These are to serve as placeholders, as many of the buttons wont work yet until we get our build settings figured out. The UI is absolutely subject to change, I'm just putting the framework here for later. In terms of code, the level select buttons are dynamically generated based on the levels in the levels[] array. That's about it, nothing is too complicated here, just setup.
> Added really basic menus

- Assets/Scenes/Technical Prototype/CharlesVehicle.unity
- Assets/Scripts/MaterialSwapper.cs
- Assets/Scripts/MaterialSwapper.cs.meta
- Assets/Scripts/Player.cs
- Player can now take damage
- Player has invincibility frames after taking damage
> Added Damage and Invincibility State

- Assets/Prefabs/AudioPrefabs.meta
- Assets/Prefabs/AudioPrefabs/AudioManager.prefab
- Assets/Prefabs/AudioPrefabs/AudioManager.prefab.meta
- Assets/Prefabs/AudioPrefabs/MusicPlayer.prefab
- Assets/Prefabs/AudioPrefabs/MusicPlayer.prefab.meta
- Assets/Scripts/AudioScripts.meta
- Assets/Scripts/AudioScripts/AudioManager.cs
- Assets/Scripts/AudioScripts/AudioManager.cs.meta
- Assets/Scripts/AudioScripts/Sound.cs
- Assets/Scripts/AudioScripts/Sound.cs.meta
- Assets/Scripts/AudioScripts/musicSwitch.cs
- Assets/Scripts/AudioScripts/musicSwitch.cs.meta
- Assets/Sounds.meta
- Assets/Sounds/Music.meta
- Assets/Sounds/Music/GrubBug Main Menu EXP4.wav.meta
- Assets/Sounds/Music/The Sizzle EXP3.wav.meta
- Assets/Sounds/SFX.meta
-Add AudioManager as a persistent audio managing tool 
-Add Sound class for storing sound effects
-Add MusicPlayer object for easy playing of music upon loading the object 
-Add two new songs
> Import audio prefabs and tools

- Assets/Scenes/Technical Prototype/AngelicaDirectionalUI.unity
- Assets/Scripts/CopAI/CopModel.cs
This week I worked on the wander state of the cops. I also added a method to damage the player. I also changed multiple fields to private for game security.
> Wander, Damage, and Changed visibility

- Assets/Scripts/Player.cs
- Both WASD and arrow keys can be used for player input
> Player Inputs Updated

- Assets/Scenes/Build/Alpha - Playtest.unity
- Assets/Scripts/OilMask.cs
- Assets/Scripts/OilMask.cs.meta
Created a script that masks the oil image according to the oil amount. Makes the oil look like it's decreasing in the UI.
> oil display masking

- Assets/Prefabs/UI_Prefabs/UI Canvas.prefab
- Assets/Scripts/OilMask.cs
> Added oil indicator

- Assets/Scripts/Player.cs
- Game goes to lose screen when player loses all health
> Lose State Added

- Assets/Scenes/Technical Prototype/EnvironmentTest.unity
- Assets/Scripts/EnvironmentScripts/Breakable.cs
- Update Environment Test scene
- Update breakable script
> Fix both game objects sharing material

- Assets/Prefabs/UI_Prefabs/SideMenu.prefab
- Assets/Prefabs/UI_Prefabs/SideMenu.prefab.meta
- Assets/Prefabs/UI_Prefabs/UI Canvas.prefab
- Assets/Scenes/Alpha/Alpha-LevelSelect.unity
- Assets/Scenes/Alpha/Alpha-LevelSelect.unity.meta
- Assets/Scenes/Alpha/Alpha-MainMenu.unity
- Assets/Scenes/Alpha/Alpha-MainMenu.unity.meta
- Assets/Scenes/Build/Alpha - Playtest.unity
- Assets/Scripts/UI/ButtonManager.cs
- Assets/Scripts/UI/ButtonManager.cs.meta
- ProjectSettings/EditorBuildSettings.asset
Created a Main Menu Scene, a Level Select Scene, and added an (invisible) pause screen to main.
Navigation between scenes function.
> Main Menu, Level Select, Pause Menu

- Assets/Prefabs/Game Prefabs/Cop Cruiser.prefab
- Assets/Scenes/Build/Alpha - Playtest.unity
- Assets/Scripts/Billboard.cs
- Assets/Scripts/CopAI/CopModel.cs
Address the concerns of the announcement on the programmer discord channel:
- Added documentation to the billboard script
- rotation angle debugging so the sprite matching is more accurate to the cop car.
> Billboard/Sprite Script Debugging

- Assets/HealthBar.cs
- Assets/Scripts/UI/HotbarManager.cs
- Assets/Scripts/UI/HotbarSlot.cs
Scripts HotbarManager.cs, HotbarSlot.cs, and HealthBar.cs have been updated to include proper documentation.
> Updated documentation for scripts

- Assets/Prefabs/AudioPrefabs/Audio Manager.prefab
- Assets/Scenes/Build/Alpha - Playtest.unity
- Assets/Scripts/AudioScripts/AudioManager.cs
- Assets/Scripts/AudioScripts/Sound.cs
- Assets/Scripts/AudioScripts/sfxPlay.cs
- Assets/Scripts/AudioScripts/sfxPlay.cs.meta
look jacob the siren can go wee woo wee woo but louder now!
> added funny reverb

- Assets/Art/StaticMesh.meta
- Assets/Material/Invisible-CastShadow.mat
- Assets/Material/Invisible-CastShadow.mat.meta
- Assets/Prefabs/Game Prefabs/Cop Cruiser.prefab
- Assets/Scenes/Build/Alpha - Playtest.unity
- Assets/Scripts/Billboard.cs
- Assets/Scripts/CopAI/CopModel.cs
- Assets/Scripts/CopAI/Pathfinding.cs
- Packages/manifest.json
- Packages/packages-lock.json
- ProjectSettings/Packages/com.unity.probuilder/Settings.json
- ProjectSettings/TagManager.asset
- fix warping of sprite near edges
- fix negative rotation of sprites
> Rotation fixes for billboard sprite script + Add shadow to prefab

- Assets/Prefabs/Game Prefabs/Game Manager.prefab
- Assets/Prefabs/UI_Prefabs/SideMenu.prefab
- Assets/Scripts/GameManager.cs
Thats it. Small change to GameManager to get reference to the panel.
> Pause Menu

- Assets/Scripts/Player/Player.cs
- Holding spacebar now slows down time for at most a second
- When you turn enough while slowed down, time goes back to normal and you will get a speed boost
> Drifting Updated

- Assets/Art/Backgrounds/Floor Tiles/Floor Palette.prefab
- Assets/Prefabs/Game Prefabs/Levels/Level 1.prefab
- Assets/Prefabs/Game Prefabs/Levels/Level 1.prefab.meta
- Assets/Scenes/Beta/Easy Level 1.unity
- Assets/Scenes/Beta/Easy Level 1.unity.meta
Implemented Easy Level (1)
-Tests out different types of customers
-City landscape to test out maneuvers with car
-Smoke for drifting effect
> Level 1 - Easy (Driving + Customers) W.I.P

- Assets/Prefabs/AudioPrefabs/Audio Manager.prefab
- Assets/Scenes/Alpha/Alpha-MainMenu.unity
- Assets/Scripts/AudioScripts/AudioManager.cs
- Assets/Scripts/AudioScripts/Sound.cs
- Assets/Scripts/CopAI/CopModel.cs
- Assets/Scripts/UI/ButtonManager.cs
- added sirens with reverb when being chased by cops
- added button click sound effects in main menu
> Sound Effect Additions

- Assets/Scripts/CustomerScripts/Customer.cs
- Assets/Scripts/Player/Player.cs
- Oil drains immediately
- Camera zooms in while drifting
- Car is less bouncy
> Charles Red Tasks Done

- Assets/Art/UI/LevelSelectUI/Idle.anim
- Assets/Art/UI/LevelSelectUI/Idle.anim.meta
- Assets/Art/UI/LevelSelectUI/LevelSelectAnimController.controller
- Assets/Art/UI/LevelSelectUI/MoveDown.anim
- Assets/Art/UI/LevelSelectUI/MoveDown.anim.meta
- Assets/Scripts/UI/LevelSelectButton.cs
- Assets/Scripts/UI/LevelSelectModal.cs
Phone no longer appears when no level is selected. Phone also goes down when level is deselected.
> fixed level select phone bug

- Assets/Prefabs/Game Prefabs/Game Manager.prefab
- Assets/Scenes/Build/Main Menu.unity
- Assets/Scripts/AudioScripts/AudioManager.cs
- Assets/Scripts/GameManager.cs
- Assets/Scripts/UI/LevelSelectButton.cs
- Assets/Scripts/UI/LevelSelectModal.cs
- Assets/Scripts/UI/SettingsManager.cs
- Assets/Scripts/UI/SettingsManager.cs.meta
- settings menu now actually works
- sirens now go away when you go back to the main menu
- clicking the Return to Main Menu or level entry buttons play the click sound effect now
> Settings and Sirens and Sounds, Oh My

- Assets/Scripts/AudioScripts/AudioManager.cs
- Assets/Scripts/GameManager.cs
> Siren fix for real

- Assets/Prefabs/Game Prefabs/Player.prefab
- Assets/Scripts/Player/Player.cs
> Drift Smoke Cooldown

- Assets/Art/cutscene.meta
- Assets/Art/cutscene/New Custom Render Texture.asset
- Assets/Art/cutscene/New Custom Render Texture.asset.meta
- Assets/Art/cutscene/gb2_3.mp4.meta
- Assets/Prefabs/Game Prefabs/Levels/emily-level-2.prefab.meta
- Assets/Prefabs/Game Prefabs/Levels/zion-level.prefab.meta
- Assets/Scenes/Build/New Render Texture.renderTexture
- Assets/Scenes/Build/New Render Texture.renderTexture.meta
- Assets/Scenes/Build/Opening Cutscence.unity
- Assets/Scenes/Build/Opening Cutscence.unity.meta
- Assets/Scripts/Cutscene.cs
- Assets/Scripts/Cutscene.cs.meta
-Added cutscene into the game
-Press any button, or click left click to skip to the main menu.
> Added Cutscene

- Assets/Prefabs/AudioPrefabs/Audio Manager.prefab
- Assets/Scenes/Build/Main Menu.unity
- Assets/Scripts/AudioScripts/AudioManager.cs
- Assets/Scripts/CopAI/CopModel.cs
Siren volume now varies as the cops get closer to the player
> Spatialized Audio Sirens
